
/**************************************************************/
/*                                                            */
/*      Copyright Mentor Graphics Corporation 2006 - 2015     */
/*                  All Rights Reserved                       */
/*                                                            */
/*       THIS WORK CONTAINS TRADE SECRET AND PROPRIETARY      */
/*         INFORMATION WHICH IS THE PROPERTY OF MENTOR        */
/*         GRAPHICS CORPORATION OR ITS LICENSORS AND IS       */
/*                 SUBJECT TO LICENSE TERMS.                  */
/*                                                            */
/**************************************************************/

//*<
//* Generated By Model Builder, Mentor Graphics Computer Systems, Inc.
//*
//* This file contains the PV class for ImageProcessing.
//* This is a template file: You may modify this file to implement the 
//* behavior of your component. 
//* 
//* Model Builder version: 4.2alpha1
//* Generated on: Feb. 15, 2016 11:27:19 AM, (user: vista)
//*>


#pragma once

#include "ImageProcessing_model.h"

using namespace tlm;

//This class inherits from the ImageProcessing_pv_base class
class ImageProcessing_pv : public ImageProcessing_pv_base {
 public:
  typedef esl::tlm_types::Address mb_address_type;
 public:
  // Constructor
  // Do not add parameters here.
  // To add parameters - use the Model Builder form (under PV->Parameters tab)
  SC_HAS_PROCESS(ImageProcessing_pv);
  ImageProcessing_pv(sc_core::sc_module_name module_name);  


typedef struct {
  unsigned char red;
  unsigned char green;
  unsigned char blue;
} pixel_t;

  double sRGB_to_linear(double x);
  double linear_to_sRGB(double y);
  void getPixel(unsigned char* bmp, int x, int y, pixel_t* p);
  void setPixel(unsigned char* bmp, int x, int y, pixel_t* p);
  void grayScale(pixel_t* p);
  void thread();

  mb::mb_fifo<unsigned> mbFifo;


 protected:
  /////////////////////////////////////////
  // write callbacks of registers
  ////////////////////////////////////////// 
  void cb_write_CONTROL(unsigned long long newValue);  

 protected:
  ////////////////////////////////////////
  // target ports read callbacks
  //////////////////////////////////////// 
  bool slave_callback_read(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_read_dbg(mb_address_type address, unsigned char* data, unsigned size); 

 protected:
  ////////////////////////////////////////
  // target ports write callbacks
  //////////////////////////////////////// 
  bool slave_callback_write(mb_address_type address, unsigned char* data, unsigned size);
  
  unsigned slave_callback_write_dbg(mb_address_type address, unsigned char* data, unsigned size); 
  virtual void cb_transport_dbg_CONTROL(tlm::tlm_generic_payload& trans); 
  bool slave_get_direct_memory_ptr(mb_address_type address, tlm::tlm_dmi& dmiData);   
};

